# Import Library

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Import Dataset

In [4]:
dataset = pd.read_csv('diabetes_prediction_dataset.csv')
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   gender               100000 non-null  object 
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64  
 3   heart_disease        100000 non-null  int64  
 4   smoking_history      100000 non-null  object 
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64  
 8   diabetes             100000 non-null  int64  
dtypes: float64(3), int64(4), object(2)
memory usage: 6.9+ MB


In [5]:
other_gender = dataset.loc[dataset['gender'] == 'Other']
# len(other_gender)
# dataset['gender'].unique()

In [6]:
dataset.isnull().any()

gender                 False
age                    False
hypertension           False
heart_disease          False
smoking_history        False
bmi                    False
HbA1c_level            False
blood_glucose_level    False
diabetes               False
dtype: bool

Berdasarkan dari code diatas, ditunjukkan bahwa dataset yang digunakan tidak ada yang kosong

In [7]:
dataset = dataset.drop_duplicates()
dataset

gender   age  hypertension  heart_disease smoking_history    bmi  \
0      Female  80.0             0              1           never  25.19   
1      Female  54.0             0              0         No Info  27.32   
2        Male  28.0             0              0           never  27.32   
3      Female  36.0             0              0         current  23.45   
4        Male  76.0             1              1         current  20.14   
...       ...   ...           ...            ...             ...    ...   
99994  Female  36.0             0              0         No Info  24.60   
99996  Female   2.0             0              0         No Info  17.37   
99997    Male  66.0             0              0          former  27.83   
99998  Female  24.0             0              0           never  35.42   
99999  Female  57.0             0              0         current  22.43   

       HbA1c_level  blood_glucose_level  diabetes  
0              6.6                  140         0  
1              6.6                   80         0  
2              5.7                  158         0  
3              5.0                  155         0  
4              4.8                  155         0  
...            ...                  ...       ...  
99994          4.8                  145         0  
99996          6.5                  100         0  
99997          5.7                  155         0  
99998          4.0                  100         0  
99999          6.6                   90         0  

[96146 rows x 9 columns]

Berdasarkan dari code diatas, ditunjukkan bahwa dataset yang digunakan terdapat data yang terduplikasi

In [8]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
dataset['gender'] = label_encoder.fit_transform(dataset['gender'])
dataset

gender   age  hypertension  heart_disease smoking_history    bmi  \
0           0  80.0             0              1           never  25.19   
1           0  54.0             0              0         No Info  27.32   
2           1  28.0             0              0           never  27.32   
3           0  36.0             0              0         current  23.45   
4           1  76.0             1              1         current  20.14   
...       ...   ...           ...            ...             ...    ...   
99994       0  36.0             0              0         No Info  24.60   
99996       0   2.0             0              0         No Info  17.37   
99997       1  66.0             0              0          former  27.83   
99998       0  24.0             0              0           never  35.42   
99999       0  57.0             0              0         current  22.43   

       HbA1c_level  blood_glucose_level  diabetes  
0              6.6                  140         0  
1              6.6                   80         0  
2              5.7                  158         0  
3              5.0                  155         0  
4              4.8                  155         0  
...            ...                  ...       ...  
99994          4.8                  145         0  
99996          6.5                  100         0  
99997          5.7                  155         0  
99998          4.0                  100         0  
99999          6.6                   90         0  

[96146 rows x 9 columns]

In [9]:
dataset = dataset[dataset['age'] > 1 ]
dataset.describe()

gender           age  hypertension  heart_disease           bmi  \
count  95153.000000  95153.000000  95153.000000   95153.000000  95153.000000   
mean       0.415037     42.224567      0.078411       0.041228     27.424858   
std        0.493115     22.179407      0.268818       0.198819      6.714516   
min        0.000000      1.080000      0.000000       0.000000     10.010000   
25%        0.000000     24.000000      0.000000       0.000000     23.560000   
50%        0.000000     43.000000      0.000000       0.000000     27.320000   
75%        1.000000     60.000000      0.000000       0.000000     29.930000   
max        2.000000     80.000000      1.000000       1.000000     95.690000   

        HbA1c_level  blood_glucose_level      diabetes  
count  95153.000000         95153.000000  95153.000000  
mean       5.534414           138.279077      0.089141  
std        1.073989            40.970627      0.284948  
min        3.500000            80.000000      0.000000  
25%        4.800000           100.000000      0.000000  
50%        5.800000           140.000000      0.000000  
75%        6.200000           159.000000      0.000000  
max        9.000000           300.000000      1.000000

In [10]:
dataset['age'] = dataset['age'].astype(int)
dataset.describe()

C:\Users\rasyi\AppData\Local\Temp\ipykernel_17872\3796267597.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['age'] = dataset['age'].astype(int)


gender           age  hypertension  heart_disease           bmi  \
count  95153.000000  95153.000000  95153.000000   95153.000000  95153.000000   
mean       0.415037     42.218932      0.078411       0.041228     27.424858   
std        0.493115     22.189801      0.268818       0.198819      6.714516   
min        0.000000      1.000000      0.000000       0.000000     10.010000   
25%        0.000000     24.000000      0.000000       0.000000     23.560000   
50%        0.000000     43.000000      0.000000       0.000000     27.320000   
75%        1.000000     60.000000      0.000000       0.000000     29.930000   
max        2.000000     80.000000      1.000000       1.000000     95.690000   

        HbA1c_level  blood_glucose_level      diabetes  
count  95153.000000         95153.000000  95153.000000  
mean       5.534414           138.279077      0.089141  
std        1.073989            40.970627      0.284948  
min        3.500000            80.000000      0.000000  
25%        4.800000           100.000000      0.000000  
50%        5.800000           140.000000      0.000000  
75%        6.200000           159.000000      0.000000  
max        9.000000           300.000000      1.000000

berdasarkan dari dataset.info() data dari kolom 'age' mempunyai type data float, lalu dirubah menjadi tipe int

In [11]:
dataset['smoking_history'].unique()

array(['never', 'No Info', 'current', 'former', 'ever', 'not current'],
      dtype=object)

In [12]:
number_smoking = {
    'never':1,
    'No Info':2,
    'current':3,
    'former':4,
    'ever':5,
    'not current':6
}

In [13]:
dataset['smoking_history'] = dataset.smoking_history.map(number_smoking)
dataset

C:\Users\rasyi\AppData\Local\Temp\ipykernel_17872\1076062665.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['smoking_history'] = dataset.smoking_history.map(number_smoking)


gender  age  hypertension  heart_disease  smoking_history    bmi  \
0           0   80             0              1                1  25.19   
1           0   54             0              0                2  27.32   
2           1   28             0              0                1  27.32   
3           0   36             0              0                3  23.45   
4           1   76             1              1                3  20.14   
...       ...  ...           ...            ...              ...    ...   
99994       0   36             0              0                2  24.60   
99996       0    2             0              0                2  17.37   
99997       1   66             0              0                4  27.83   
99998       0   24             0              0                1  35.42   
99999       0   57             0              0                3  22.43   

       HbA1c_level  blood_glucose_level  diabetes  
0              6.6                  140         0  
1              6.6                   80         0  
2              5.7                  158         0  
3              5.0                  155         0  
4              4.8                  155         0  
...            ...                  ...       ...  
99994          4.8                  145         0  
99996          6.5                  100         0  
99997          5.7                  155         0  
99998          4.0                  100         0  
99999          6.6                   90         0  

[95153 rows x 9 columns]

## Split data

In [14]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0 )

In [16]:
X_train

array([[  0.  ,  55.  ,   0.  , ...,  27.32,   5.  , 155.  ],
       [  1.  ,  48.  ,   0.  , ...,  34.85,   4.  ,  90.  ],
       [  0.  ,  80.  ,   0.  , ...,  22.95,   6.  ,  85.  ],
       ...,
       [  0.  ,  13.  ,   0.  , ...,  20.32,   6.1 , 200.  ],
       [  0.  ,  45.  ,   0.  , ...,  37.13,   6.2 , 130.  ],
       [  1.  ,  22.  ,   0.  , ...,  27.32,   6.5 , 200.  ]])

## Feature Scalling

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Feature scalling tidak dapat dilakukan ke dalam kolom yang kategorikal (0-1/True-False). Biasanya dilakukan pada data yang mempunyai jarak yang jauh dan juga dilakukan ke dalam model yang sensitif.

In [18]:
X_train

array([[-0.84224601,  0.57535041, -0.29280621, ..., -0.01618012,
        -0.49797338,  0.40482047],
       [ 1.18563389,  0.25991685, -0.29280621, ...,  1.1067195 ,
        -1.42874349, -1.18178923],
       [-0.84224601,  1.70189886, -0.29280621, ..., -0.66784961,
         0.43279673, -1.30383613],
       ...,
       [-0.84224601, -1.31725098, -0.29280621, ..., -1.0600443 ,
         0.52587374,  1.50324257],
       [-0.84224601,  0.12473103, -0.29280621, ...,  1.44672097,
         0.61895075, -0.20541403],
       [ 1.18563389, -0.91169354, -0.29280621, ..., -0.01618012,
         0.89818179,  1.50324257]])

# Logistic Regression

In [19]:
from sklearn.linear_model import LogisticRegression
regressor = LogisticRegression(random_state=0)
regressor.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [20]:
y_regressor = regressor.predict(X_test)
print(np.concatenate((y_regressor.reshape(len(y_regressor), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 0]
 [1 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_regressor)
print(cm)

[[17184   174]
 [  603  1070]]


# K-NN

In [22]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5, p=2, metric='minkowski')
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [23]:
y_knn = classifier.predict(X_test)
print(np.concatenate((y_knn.reshape(len(y_knn), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 0]
 [1 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_knn)
print(cm)

[[17227   131]
 [  645  1028]]


# SVM

In [26]:
from sklearn.svm import SVC
svm = SVC(kernel='linear', random_state=0)
svm.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [27]:
y_pred_linear = svm.predict(X_test)
print(np.concatenate((y_pred_linear.reshape(len(y_pred_linear), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 0]
 [1 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_linear)
print(cm)

[[17264    94]
 [  675   998]]


# SVM (RBF)

In [29]:
from sklearn.svm import SVC
brf = SVC(kernel='rbf', random_state=0)
brf.fit(X_train, y_train)

SVC(random_state=0)

In [30]:
y_pred_rbf = brf.predict(X_test)
print(np.concatenate((y_pred_rbf.reshape(len(y_pred_rbf), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 0]
 [1 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_rbf)
print(cm)

[[17336    22]
 [  687   986]]


# Naive Baiyes

In [32]:
from sklearn.naive_bayes import GaussianNB
naive_baiyes = GaussianNB()
naive_baiyes.fit(X_train, y_train)

GaussianNB()

In [33]:
y_pred_nb = naive_baiyes.predict(X_test)
print(np.concatenate((y_pred_nb.reshape(len(y_pred_nb), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 0]
 [1 1]
 ...
 [1 0]
 [0 0]
 [0 0]]


In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_nb)
print(cm)

[[16083  1275]
 [  585  1088]]


# Decision Tree

In [35]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(criterion='entropy', random_state=0)
dt.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [36]:
y_pred_dt = dt.predict(X_test)
print(np.concatenate((y_pred_dt.reshape(len(y_pred_dt), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 0]
 [1 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_dt)
print(cm)

[[16841   517]
 [  445  1228]]


# Random Forest

In [38]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)
rf.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [39]:
y_pred_rf = rf.predict(X_test)
print(np.concatenate((y_pred_rf.reshape(len(y_pred_rf), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 0]
 [1 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_rf)
print(cm)

[[17281    77]
 [  517  1156]]


# Evaluation

In [41]:
#Logsitic Regression
accuracy_score(y_test, y_regressor)

0.9591718774630865

In [42]:
#KNN
accuracy_score(y_test, y_knn)

0.9592244233093374

In [43]:
#SVM Kernel Linear
accuracy_score(y_test, y_pred_linear)

0.9595922442330934

In [44]:
#SVM Kernel RBF
accuracy_score(y_test, y_pred_rbf)

0.9627449950081446

In [45]:
#Naive Baiyes
accuracy_score(y_test, y_pred_nb)

0.9022647259734118

In [46]:
#Decision Tree
accuracy_score(y_test, y_pred_dt)

0.9494508959066785

In [47]:
#Random Forest
accuracy_score(y_test, y_pred_rf)

0.9687877673269928