# SVR Regression

## Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the dataset

In [34]:
# Enter name of the dataset.csv
dataset = pd.read_csv('DataListrik.csv')
X = np.array(dataset.iloc[:,:-1])
y = np.array(dataset.iloc[:,-1])
y = y.reshape(len(y),1)

## Splitting dataset into training set and test set

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0 )

In [27]:
X_train

array([[  11.22,   43.13, 1017.24,   80.9 ],
       [  13.67,   54.3 , 1015.92,   75.42],
       [  32.84,   77.95, 1014.68,   45.8 ],
       ...,
       [  16.81,   38.52, 1018.26,   75.21],
       [  12.8 ,   41.16, 1022.43,   86.19],
       [  32.32,   67.9 , 1006.08,   37.93]])

In [23]:
X_test

array([[  28.66,   77.95, 1009.56,   69.07],
       [  17.48,   49.39, 1021.51,   84.53],
       [  14.86,   43.14, 1019.21,   99.14],
       ...,
       [  12.24,   44.92, 1023.74,   88.21],
       [  27.28,   47.93, 1003.46,   59.22],
       [  17.28,   39.99, 1007.09,   74.25]])

## Scalling data

In [36]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
y_train = sc_y.fit_transform(y_train)

In [29]:
X_train

array([[-1.14, -0.89,  0.67,  0.52],
       [-0.81, -0.01,  0.45,  0.15],
       [ 1.77,  1.85,  0.24, -1.88],
       ...,
       [-0.38, -1.25,  0.85,  0.13],
       [-0.92, -1.04,  1.55,  0.88],
       [ 1.7 ,  1.06, -1.2 , -2.42]])

In [30]:
y_train

array([[ 1.15],
       [ 0.8 ],
       [-1.31],
       ...,
       [ 0.28],
       [ 0.49],
       [-1.54]])

## Training the SVR Regression model on the Training set

In [11]:
from sklearn.svm import SVR
regressor = SVR(kernel='rbf')
#X,y disini adalah X,y yang sudah mengalami transformasi scalling
regressor.fit(X_train,y_train)

/home/irfan/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

## Predicting the test set results

In [17]:
y_pred = sc_y.inverse_transform(regressor.predict(sc_X.transform(X_test)).reshape(-1,1))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[434.5  431.23]
 [457.71 460.01]
 [460.85 461.14]
 ...
 [470.22 473.26]
 [439.29 438.  ]
 [460.43 463.28]]


In [16]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9483693304317924